# Generated by Django 4.0.6 on 2023-08-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_pms', '0006_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('cleaning', 'Needs Cleaning'), ('maintenance', 'Needs Maintenance')], default='available', max_length=12),
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
