# Generated by Django 4.0.6 on 2023-08-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_pms', '0007_room_status_delete_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='basic', max_length=255),
        ),
    ]
