# Generated by Django 4.0.6 on 2023-08-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_pms', '0008_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
