# Generated by Django 4.0.6 on 2023-08-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_pms', '0010_roomimage_remove_feedback_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='approval',
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='rooms/'),
        ),
    ]
