# Generated by Django 4.0.6 on 2023-08-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_pms', '0013_extracharge_bookingcharge_booking_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
