# Generated by Django 4.0.6 on 2023-08-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_pms', '0014_customer_is_blacklisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bookingcharge',
            unique_together=set(),
        ),
    ]
