# Generated by Django 4.0.6 on 2023-08-29 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_pms', '0015_adminnotes_alter_bookingcharge_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Employees',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='staff',
            new_name='employees',
        ),
    ]
