# Generated by Django 4.2.1 on 2023-09-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_pms', '0016_rename_staff_employees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffregistrationrequest',
            old_name='staff_id',
            new_name='employee_id',
        ),
    ]
